---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)
```

## `pivot_longer`

Load the pulse data

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()

pulse_df
```

Go from wide format to long format
```{r}
pulse_tidy_df = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_df
```

Rewrite, combine, and extend (add mutate)
```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") |>
  relocate(id, visit) |>
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)) 
```

## `pivot_wider`

make up some data

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result
```

```{r}
pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")
```


## Binding rows using LorR data, combine multiple tables

First step: import each

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```

Bind all the rows together

```{r}
lotr_tidy =
  bind_rows(fellowship_ring, two_towers, return_king)|>
  janitor::clean_names()|>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words")|> 
  select(movie, everything()) 
```






